version: '3.5'

services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:3.1
    ports:
      - 4000
    container_name: avatar-service
    working_dir: /src
    command: >
      bash -c "dotnet restore && dotnet build && dotnet bin/Debug/netcoreapp3.1/WebApi.dll"
    volumes:
      - .:/src
    networks:
      - main_network

networks:
  main_network:
    name: swarley_network